# Generated by Django 5.1.2 on 2024-10-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('years', models.PositiveIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('access_level', models.CharField(choices=[('all', '모두 열람 가능'), ('staff', 'Staff 및 Superuser 전용'), ('superuser', 'Superuser 전용')], default='all', max_length=10)),
                ('parent_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_modules', to='wiki.textmodule')),
            ],
        ),
        migrations.CreateModel(
            name='TextModuleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wiki.textmodule')),
            ],
        ),
    ]
