# Generated by Django 5.1.2 on 2024-10-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodule',
            name='slug',
            field=models.SlugField(),
        ),
    ]
