# Generated by Django 5.1.2 on 2024-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_textmodule_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='textmodule',
            constraint=models.UniqueConstraint(fields=('title', 'years'), name='unique_title_years'),
        ),
    ]
