# Generated by Django 5.1.2 on 2024-10-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_remove_textmodule_unique_title_years_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='textmodule',
            name='unique_parent_title_years',
        ),
    ]
