# Generated by Django 5.1.2 on 2024-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_remove_textmodule_unique_parent_title_years'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='textmodule',
            constraint=models.UniqueConstraint(fields=('parent_module', 'title', 'years'), name='unique_parent_title_years'),
        ),
    ]
