# Generated by Django 5.1.2 on 2024-11-14 12:08

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_textmodule_unique_parent_title_years'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='textmodule',
            name='unique_parent_title_years',
        ),
        migrations.AlterField(
            model_name='textmodulefile',
            name='file',
            field=models.FileField(upload_to=wiki.models.upload_to_module_directory),
        ),
        migrations.AddConstraint(
            model_name='textmodule',
            constraint=models.UniqueConstraint(fields=('title', 'years'), name='unique_title_years'),
        ),
    ]
